expname: 4column250311_307_seed_2
data:
  datadir: [data/rename/RS307]
  far: 4.5
  fov: 25
  imsize: 128  
  near: 1.5
  orthographic: False
  use_default_rays : False
  radius: 3.
  type: RS307_0_i2
  umax: 1.
  umin: 0.
  vmax: 0.5
  vmin: 0.
  # v: 0.4166667, 0.3333334, 0.25, 0.1666667, 0.1166667
  v: 0.5, 0.4166667, 0.3333334, 0.25, 0.1666667  #90 80.406 70.529 60 48.19
discriminator:
  num_classes: 4   
  hflip: false
  ndf: 64 #64 #128
nerf:
  N_samples: 64
  decrease_noise: true
  i_embed: 0
  multires: 10
  multires_views: 4
  netdepth: 8
  netwidth: 256
  perturb: 1.0
  raw_noise_std: 1.0
  use_viewdirs: true
  N_importance: 0
  netdepth_fine: 8
  netwidth_fine: 256
ray_sampler:
  N_samples: 1024 #1024 #4096
  max_scale: 1.0
  min_scale: 0.25
  scale_anneal: 0.0025
training:
  backup_every: 50000
  batch_size: 8
  chunk: 32768 #131072
  equalize_lr: false
  fid_every: 5000
  gan_type: standard
  lr_anneal: 0.5
  lr_anneal_every: 50000,100000,200000
  lr_d: 0.0001
  lr_g: 0.0005
  model_average_beta: 0.999
  model_average_reinit: false
  model_file: model.pt
  netchunk: 65536 #262144
  nworkers: 0
  optimizer: rmsprop
  outdir: ./results
  print_every: 10
  reg_param: 10.0
  restart_every: -1
  sample_every: 500
  save_best: fid
  save_every: 1000
z_dist:
  dim: 256
  type: gauss
